### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by rernst** [UMCUGenetics/NextflowModules#1]
## Modules
- [ ] Singularity / Guix usage.
- [ ] How to name input / output files?
- [ ] How to set publishDir?
- [ ] Cluster settings based on input? (WES vs WGS).
- [ ] Pipes support (https://www.nextflow.io/docs/edge/dsl2.html#pipes)

## Repository
- [ ] Implement automated testing?

## Readme
- [ ] How to use this repository.
- [ ] Update contribution guidelines
